# Stage 1: Build React app

FROM node:18-alpine AS builder

WORKDIR /app

# Copy dependency files first for Docker cache

COPY package*.json ./
RUN npm install

# Copy the rest of the project files

COPY . .

# Build production bundle

RUN npm run build

# Stage 2: Serve with NGINX

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copy built static files from builder stage

COPY --from=builder /app/build .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
