#stage 1 
FROM maven:3.9.6-eclipse-temurin-17-alpine AS builder

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package

COPY . .

#stage 2
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=builder /app .
CMD ["java", "-jar", "target/order-service-1.0.jar"]