### Health Check
GET http://localhost:3003/health


### Get Products
GET http://localhost:3003/products


### Add Product
POST http://localhost:3003/products
Content-Type: application/json

{
  "name": "New Product"
}