#Stage - 1 
FROM python:3.10-alpine AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .


#Stage - 2
FROM python:3.10-alpine
WORKDIR /app
COPY --from=builder /app .
RUN pip install -r requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]